### ISSUE TITLE
Add management apps

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-dockerfiles#13]
Create metadata-mgmt and data-mgmt images and add them to docker-compose.yaml to create a complete environment with management apps. This will help with testing and development using docker.

**Comment by luan-cestari** [comment]
Agree. I forgot about them, but I thought something similar on https://github.com/lightblue-platform/lightblue-dockerfiles/issues/14 (just created it)

**Comment by paterczm** [comment]
Done.
