### ISSUE TITLE
Error crud:NoAccess ?

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-dockerfiles#17]
Getting this using the setup provided by Dockerfiles here. I expected there to be no permissions issues using the services in these images... am I missing something or are the images not setup for no-auth correctly?

**Comment by paterczm** [comment]
This can happen if you have access configured to anything else than 'anyone' in your schema.

**Comment by alechenninger** [comment]
Ah, probably user error then, since I don't really fully understand the schema and if I setting it up correctly (it'd be great if there was a sample schema / datastore setup!)

I'll close unless I can still reproduce with a correct schema
