### ISSUE TITLE
Prepare wildfly docker image for lightblue 2.7.0

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-dockerfiles#24]
So far we've been using JBoss AS 7 and openjdk 7 to run Lightblue in docker container. Newer Lightblue builds require java 8, which means we should deploy Lightblue in Wildfly now. I vaguely remember there were some problems with weld dependencies on Wildfly last time we tried.

**Comment by bserdar** [comment]
I deployed the no-auth version on wildfly 10 without any problems.

**Comment by paterczm** [comment]
You're right, no problems this time.
